FROM mariadb:11

RUN apt-get update && \
    apt-get install -y curl && \
    mkdir -p /opt/flink/lib && \
    curl -Lo /opt/flink/lib/flink-sql-connector-mysql-cdc-3.0.1.jar https://repo1.maven.org/maven2/com/ververica/flink-sql-connector-mysql-cdc/3.0.1/flink-sql-connector-mysql-cdc-3.0.1.jar && \
    curl -Lo /opt/flink/lib/flink-shaded-hadoop-2-uber-2.7.5-10.0.jar https://repo.maven.apache.org/maven2/org/apache/flink/flink-shaded-hadoop-2-uber/2.7.5-10.0/flink-shaded-hadoop-2-uber-2.7.5-10.0.jar && \
    curl -Lo /opt/flink/lib/iceberg-flink-runtime-1.16-1.3.1.jar https://repo.maven.apache.org/maven2/org/apache/iceberg/iceberg-flink-runtime-1.16/1.3.1/iceberg-flink-runtime-1.16-1.3.1.jar

USER root

# Scripts placed here will automatically run when the container starts
COPY scripts/create_tables.sql /docker-entrypoint-initdb.d/

RUN chmod +x /docker-entrypoint-initdb.d/create_tables.sql

CMD ["--log-bin=/var/log/mysql/mariadb-bin", "--binlog-format=ROW"]